// <auto-generated>
//     Generated by tools/generate.py — do not edit by hand.
//     Re-run: python3 tools/generate.py
// </auto-generated>

namespace Stringly.Nato;

/// <summary>
/// Chain-<b>starting</b> entries. Import with <c>using static Stringly.Nato.Start;</c>
/// to begin a chain with a bare call.
/// </summary>
public static class Start
{
    /// <summary>Starts a phrase with <c>A</c>.</summary>
    public static Phrase Alfa() => Phrase.Empty.Add('A');
    /// <summary>Starts a phrase with <c>B</c>.</summary>
    public static Phrase Bravo() => Phrase.Empty.Add('B');
    /// <summary>Starts a phrase with <c>C</c>.</summary>
    public static Phrase Charlie() => Phrase.Empty.Add('C');
    /// <summary>Starts a phrase with <c>D</c>.</summary>
    public static Phrase Delta() => Phrase.Empty.Add('D');
    /// <summary>Starts a phrase with <c>E</c>.</summary>
    public static Phrase Echo() => Phrase.Empty.Add('E');
    /// <summary>Starts a phrase with <c>F</c>.</summary>
    public static Phrase Foxtrot() => Phrase.Empty.Add('F');
    /// <summary>Starts a phrase with <c>G</c>.</summary>
    public static Phrase Golf() => Phrase.Empty.Add('G');
    /// <summary>Starts a phrase with <c>H</c>.</summary>
    public static Phrase Hotel() => Phrase.Empty.Add('H');
    /// <summary>Starts a phrase with <c>I</c>.</summary>
    public static Phrase India() => Phrase.Empty.Add('I');
    /// <summary>Starts a phrase with <c>J</c>.</summary>
    public static Phrase Juliett() => Phrase.Empty.Add('J');
    /// <summary>Starts a phrase with <c>K</c>.</summary>
    public static Phrase Kilo() => Phrase.Empty.Add('K');
    /// <summary>Starts a phrase with <c>L</c>.</summary>
    public static Phrase Lima() => Phrase.Empty.Add('L');
    /// <summary>Starts a phrase with <c>M</c>.</summary>
    public static Phrase Mike() => Phrase.Empty.Add('M');
    /// <summary>Starts a phrase with <c>N</c>.</summary>
    public static Phrase November() => Phrase.Empty.Add('N');
    /// <summary>Starts a phrase with <c>O</c>.</summary>
    public static Phrase Oscar() => Phrase.Empty.Add('O');
    /// <summary>Starts a phrase with <c>P</c>.</summary>
    public static Phrase Papa() => Phrase.Empty.Add('P');
    /// <summary>Starts a phrase with <c>Q</c>.</summary>
    public static Phrase Quebec() => Phrase.Empty.Add('Q');
    /// <summary>Starts a phrase with <c>R</c>.</summary>
    public static Phrase Romeo() => Phrase.Empty.Add('R');
    /// <summary>Starts a phrase with <c>S</c>.</summary>
    public static Phrase Sierra() => Phrase.Empty.Add('S');
    /// <summary>Starts a phrase with <c>T</c>.</summary>
    public static Phrase Tango() => Phrase.Empty.Add('T');
    /// <summary>Starts a phrase with <c>U</c>.</summary>
    public static Phrase Uniform() => Phrase.Empty.Add('U');
    /// <summary>Starts a phrase with <c>V</c>.</summary>
    public static Phrase Victor() => Phrase.Empty.Add('V');
    /// <summary>Starts a phrase with <c>W</c>.</summary>
    public static Phrase Whiskey() => Phrase.Empty.Add('W');
    /// <summary>Starts a phrase with <c>X</c>.</summary>
    public static Phrase Xray() => Phrase.Empty.Add('X');
    /// <summary>Starts a phrase with <c>Y</c>.</summary>
    public static Phrase Yankee() => Phrase.Empty.Add('Y');
    /// <summary>Starts a phrase with <c>Z</c>.</summary>
    public static Phrase Zulu() => Phrase.Empty.Add('Z');
}

/// <summary>
/// Chain-<b>continuing</b> tokens. Available with <c>using Stringly.Nato;</c>.
/// Hand-written macros, if any, live in a separate partial of this class.
/// </summary>
public static partial class NatoExtensions
{
    /// <summary>Continues a chain with <c>A</c>.</summary>
    public static Phrase Alfa(this Phrase p) => p.Add('A');
    /// <summary>Continues a chain with <c>B</c>.</summary>
    public static Phrase Bravo(this Phrase p) => p.Add('B');
    /// <summary>Continues a chain with <c>C</c>.</summary>
    public static Phrase Charlie(this Phrase p) => p.Add('C');
    /// <summary>Continues a chain with <c>D</c>.</summary>
    public static Phrase Delta(this Phrase p) => p.Add('D');
    /// <summary>Continues a chain with <c>E</c>.</summary>
    public static Phrase Echo(this Phrase p) => p.Add('E');
    /// <summary>Continues a chain with <c>F</c>.</summary>
    public static Phrase Foxtrot(this Phrase p) => p.Add('F');
    /// <summary>Continues a chain with <c>G</c>.</summary>
    public static Phrase Golf(this Phrase p) => p.Add('G');
    /// <summary>Continues a chain with <c>H</c>.</summary>
    public static Phrase Hotel(this Phrase p) => p.Add('H');
    /// <summary>Continues a chain with <c>I</c>.</summary>
    public static Phrase India(this Phrase p) => p.Add('I');
    /// <summary>Continues a chain with <c>J</c>.</summary>
    public static Phrase Juliett(this Phrase p) => p.Add('J');
    /// <summary>Continues a chain with <c>K</c>.</summary>
    public static Phrase Kilo(this Phrase p) => p.Add('K');
    /// <summary>Continues a chain with <c>L</c>.</summary>
    public static Phrase Lima(this Phrase p) => p.Add('L');
    /// <summary>Continues a chain with <c>M</c>.</summary>
    public static Phrase Mike(this Phrase p) => p.Add('M');
    /// <summary>Continues a chain with <c>N</c>.</summary>
    public static Phrase November(this Phrase p) => p.Add('N');
    /// <summary>Continues a chain with <c>O</c>.</summary>
    public static Phrase Oscar(this Phrase p) => p.Add('O');
    /// <summary>Continues a chain with <c>P</c>.</summary>
    public static Phrase Papa(this Phrase p) => p.Add('P');
    /// <summary>Continues a chain with <c>Q</c>.</summary>
    public static Phrase Quebec(this Phrase p) => p.Add('Q');
    /// <summary>Continues a chain with <c>R</c>.</summary>
    public static Phrase Romeo(this Phrase p) => p.Add('R');
    /// <summary>Continues a chain with <c>S</c>.</summary>
    public static Phrase Sierra(this Phrase p) => p.Add('S');
    /// <summary>Continues a chain with <c>T</c>.</summary>
    public static Phrase Tango(this Phrase p) => p.Add('T');
    /// <summary>Continues a chain with <c>U</c>.</summary>
    public static Phrase Uniform(this Phrase p) => p.Add('U');
    /// <summary>Continues a chain with <c>V</c>.</summary>
    public static Phrase Victor(this Phrase p) => p.Add('V');
    /// <summary>Continues a chain with <c>W</c>.</summary>
    public static Phrase Whiskey(this Phrase p) => p.Add('W');
    /// <summary>Continues a chain with <c>X</c>.</summary>
    public static Phrase Xray(this Phrase p) => p.Add('X');
    /// <summary>Continues a chain with <c>Y</c>.</summary>
    public static Phrase Yankee(this Phrase p) => p.Add('Y');
    /// <summary>Continues a chain with <c>Z</c>.</summary>
    public static Phrase Zulu(this Phrase p) => p.Add('Z');
}
