// <auto-generated>
//     Generated by tools/generate.py — do not edit by hand.
//     Re-run: python3 tools/generate.py
// </auto-generated>

namespace Stringly.Emoji;

/// <summary>
/// Chain-<b>starting</b> entries. Import with <c>using static Stringly.Emoji.Start;</c>
/// to begin a chain with a bare call.
/// </summary>
public static class Start
{
    /// <summary>Starts a phrase with <c>😀</c>.</summary>
    public static Phrase Grin() => Phrase.Empty.Add("😀");
    /// <summary>Starts a phrase with <c>😂</c>.</summary>
    public static Phrase Joy() => Phrase.Empty.Add("😂");
    /// <summary>Starts a phrase with <c>😉</c>.</summary>
    public static Phrase Wink() => Phrase.Empty.Add("😉");
    /// <summary>Starts a phrase with <c>😎</c>.</summary>
    public static Phrase Cool() => Phrase.Empty.Add("😎");
    /// <summary>Starts a phrase with <c>😢</c>.</summary>
    public static Phrase Cry() => Phrase.Empty.Add("😢");
    /// <summary>Starts a phrase with <c>❤️</c>.</summary>
    public static Phrase Heart() => Phrase.Empty.Add("❤️");
    /// <summary>Starts a phrase with <c>👍</c>.</summary>
    public static Phrase ThumbsUp() => Phrase.Empty.Add("👍");
    /// <summary>Starts a phrase with <c>👎</c>.</summary>
    public static Phrase ThumbsDown() => Phrase.Empty.Add("👎");
    /// <summary>Starts a phrase with <c>👏</c>.</summary>
    public static Phrase Clap() => Phrase.Empty.Add("👏");
    /// <summary>Starts a phrase with <c>👋</c>.</summary>
    public static Phrase Wave() => Phrase.Empty.Add("👋");
    /// <summary>Starts a phrase with <c>🔥</c>.</summary>
    public static Phrase Fire() => Phrase.Empty.Add("🔥");
    /// <summary>Starts a phrase with <c>🚀</c>.</summary>
    public static Phrase Rocket() => Phrase.Empty.Add("🚀");
    /// <summary>Starts a phrase with <c>🎉</c>.</summary>
    public static Phrase Party() => Phrase.Empty.Add("🎉");
    /// <summary>Starts a phrase with <c>💯</c>.</summary>
    public static Phrase Hundred() => Phrase.Empty.Add("💯");
    /// <summary>Starts a phrase with <c>✨</c>.</summary>
    public static Phrase Sparkles() => Phrase.Empty.Add("✨");
    /// <summary>Starts a phrase with <c>👀</c>.</summary>
    public static Phrase Eyes() => Phrase.Empty.Add("👀");
    /// <summary>Starts a phrase with <c>💀</c>.</summary>
    public static Phrase Skull() => Phrase.Empty.Add("💀");
    /// <summary>Starts a phrase with <c>💩</c>.</summary>
    public static Phrase Poop() => Phrase.Empty.Add("💩");
    /// <summary>Starts a phrase with <c>✅</c>.</summary>
    public static Phrase Check() => Phrase.Empty.Add("✅");
    /// <summary>Starts a phrase with <c>❌</c>.</summary>
    public static Phrase Cross() => Phrase.Empty.Add("❌");
    /// <summary>Starts a phrase with <c>🐱</c>.</summary>
    public static Phrase Cat() => Phrase.Empty.Add("🐱");
    /// <summary>Starts a phrase with <c>🐶</c>.</summary>
    public static Phrase Dog() => Phrase.Empty.Add("🐶");
    /// <summary>Starts a phrase with <c>🍕</c>.</summary>
    public static Phrase Pizza() => Phrase.Empty.Add("🍕");
    /// <summary>Starts a phrase with <c>☕</c>.</summary>
    public static Phrase Coffee() => Phrase.Empty.Add("☕");
    /// <summary>Starts a phrase with <c>🍺</c>.</summary>
    public static Phrase Beer() => Phrase.Empty.Add("🍺");
    /// <summary>Starts a phrase with <c>🌈</c>.</summary>
    public static Phrase Rainbow() => Phrase.Empty.Add("🌈");
    /// <summary>Starts a phrase with <c>☀️</c>.</summary>
    public static Phrase Sun() => Phrase.Empty.Add("☀️");
    /// <summary>Starts a phrase with <c>🌙</c>.</summary>
    public static Phrase Moon() => Phrase.Empty.Add("🌙");
}

/// <summary>
/// Chain-<b>continuing</b> tokens. Available with <c>using Stringly.Emoji;</c>.
/// Hand-written macros, if any, live in a separate partial of this class.
/// </summary>
public static partial class EmojiExtensions
{
    /// <summary>Continues a chain with <c>😀</c>.</summary>
    public static Phrase Grin(this Phrase p) => p.Add("😀");
    /// <summary>Continues a chain with <c>😂</c>.</summary>
    public static Phrase Joy(this Phrase p) => p.Add("😂");
    /// <summary>Continues a chain with <c>😉</c>.</summary>
    public static Phrase Wink(this Phrase p) => p.Add("😉");
    /// <summary>Continues a chain with <c>😎</c>.</summary>
    public static Phrase Cool(this Phrase p) => p.Add("😎");
    /// <summary>Continues a chain with <c>😢</c>.</summary>
    public static Phrase Cry(this Phrase p) => p.Add("😢");
    /// <summary>Continues a chain with <c>❤️</c>.</summary>
    public static Phrase Heart(this Phrase p) => p.Add("❤️");
    /// <summary>Continues a chain with <c>👍</c>.</summary>
    public static Phrase ThumbsUp(this Phrase p) => p.Add("👍");
    /// <summary>Continues a chain with <c>👎</c>.</summary>
    public static Phrase ThumbsDown(this Phrase p) => p.Add("👎");
    /// <summary>Continues a chain with <c>👏</c>.</summary>
    public static Phrase Clap(this Phrase p) => p.Add("👏");
    /// <summary>Continues a chain with <c>👋</c>.</summary>
    public static Phrase Wave(this Phrase p) => p.Add("👋");
    /// <summary>Continues a chain with <c>🔥</c>.</summary>
    public static Phrase Fire(this Phrase p) => p.Add("🔥");
    /// <summary>Continues a chain with <c>🚀</c>.</summary>
    public static Phrase Rocket(this Phrase p) => p.Add("🚀");
    /// <summary>Continues a chain with <c>🎉</c>.</summary>
    public static Phrase Party(this Phrase p) => p.Add("🎉");
    /// <summary>Continues a chain with <c>💯</c>.</summary>
    public static Phrase Hundred(this Phrase p) => p.Add("💯");
    /// <summary>Continues a chain with <c>✨</c>.</summary>
    public static Phrase Sparkles(this Phrase p) => p.Add("✨");
    /// <summary>Continues a chain with <c>👀</c>.</summary>
    public static Phrase Eyes(this Phrase p) => p.Add("👀");
    /// <summary>Continues a chain with <c>💀</c>.</summary>
    public static Phrase Skull(this Phrase p) => p.Add("💀");
    /// <summary>Continues a chain with <c>💩</c>.</summary>
    public static Phrase Poop(this Phrase p) => p.Add("💩");
    /// <summary>Continues a chain with <c>✅</c>.</summary>
    public static Phrase Check(this Phrase p) => p.Add("✅");
    /// <summary>Continues a chain with <c>❌</c>.</summary>
    public static Phrase Cross(this Phrase p) => p.Add("❌");
    /// <summary>Continues a chain with <c>🐱</c>.</summary>
    public static Phrase Cat(this Phrase p) => p.Add("🐱");
    /// <summary>Continues a chain with <c>🐶</c>.</summary>
    public static Phrase Dog(this Phrase p) => p.Add("🐶");
    /// <summary>Continues a chain with <c>🍕</c>.</summary>
    public static Phrase Pizza(this Phrase p) => p.Add("🍕");
    /// <summary>Continues a chain with <c>☕</c>.</summary>
    public static Phrase Coffee(this Phrase p) => p.Add("☕");
    /// <summary>Continues a chain with <c>🍺</c>.</summary>
    public static Phrase Beer(this Phrase p) => p.Add("🍺");
    /// <summary>Continues a chain with <c>🌈</c>.</summary>
    public static Phrase Rainbow(this Phrase p) => p.Add("🌈");
    /// <summary>Continues a chain with <c>☀️</c>.</summary>
    public static Phrase Sun(this Phrase p) => p.Add("☀️");
    /// <summary>Continues a chain with <c>🌙</c>.</summary>
    public static Phrase Moon(this Phrase p) => p.Add("🌙");
}
