// <auto-generated>
//     Generated by tools/generate.py — do not edit by hand.
//     Re-run: python3 tools/generate.py
// </auto-generated>

namespace Stringly.Greek;

/// <summary>
/// Chain-<b>starting</b> entries. Import with <c>using static Stringly.Greek.Start;</c>
/// to begin a chain with a bare call.
/// </summary>
public static class Start
{
    /// <summary>Starts a phrase with <c>α</c>.</summary>
    public static Phrase Alpha() => Phrase.Empty.Add('α');
    /// <summary>Starts a phrase with <c>β</c>.</summary>
    public static Phrase Beta() => Phrase.Empty.Add('β');
    /// <summary>Starts a phrase with <c>γ</c>.</summary>
    public static Phrase Gamma() => Phrase.Empty.Add('γ');
    /// <summary>Starts a phrase with <c>δ</c>.</summary>
    public static Phrase Delta() => Phrase.Empty.Add('δ');
    /// <summary>Starts a phrase with <c>ε</c>.</summary>
    public static Phrase Epsilon() => Phrase.Empty.Add('ε');
    /// <summary>Starts a phrase with <c>ζ</c>.</summary>
    public static Phrase Zeta() => Phrase.Empty.Add('ζ');
    /// <summary>Starts a phrase with <c>η</c>.</summary>
    public static Phrase Eta() => Phrase.Empty.Add('η');
    /// <summary>Starts a phrase with <c>θ</c>.</summary>
    public static Phrase Theta() => Phrase.Empty.Add('θ');
    /// <summary>Starts a phrase with <c>ι</c>.</summary>
    public static Phrase Iota() => Phrase.Empty.Add('ι');
    /// <summary>Starts a phrase with <c>κ</c>.</summary>
    public static Phrase Kappa() => Phrase.Empty.Add('κ');
    /// <summary>Starts a phrase with <c>λ</c>.</summary>
    public static Phrase Lambda() => Phrase.Empty.Add('λ');
    /// <summary>Starts a phrase with <c>μ</c>.</summary>
    public static Phrase Mu() => Phrase.Empty.Add('μ');
    /// <summary>Starts a phrase with <c>ν</c>.</summary>
    public static Phrase Nu() => Phrase.Empty.Add('ν');
    /// <summary>Starts a phrase with <c>ξ</c>.</summary>
    public static Phrase Xi() => Phrase.Empty.Add('ξ');
    /// <summary>Starts a phrase with <c>ο</c>.</summary>
    public static Phrase Omicron() => Phrase.Empty.Add('ο');
    /// <summary>Starts a phrase with <c>π</c>.</summary>
    public static Phrase Pi() => Phrase.Empty.Add('π');
    /// <summary>Starts a phrase with <c>ρ</c>.</summary>
    public static Phrase Rho() => Phrase.Empty.Add('ρ');
    /// <summary>Starts a phrase with <c>σ</c>.</summary>
    public static Phrase Sigma() => Phrase.Empty.Add('σ');
    /// <summary>Starts a phrase with <c>τ</c>.</summary>
    public static Phrase Tau() => Phrase.Empty.Add('τ');
    /// <summary>Starts a phrase with <c>υ</c>.</summary>
    public static Phrase Upsilon() => Phrase.Empty.Add('υ');
    /// <summary>Starts a phrase with <c>φ</c>.</summary>
    public static Phrase Phi() => Phrase.Empty.Add('φ');
    /// <summary>Starts a phrase with <c>χ</c>.</summary>
    public static Phrase Chi() => Phrase.Empty.Add('χ');
    /// <summary>Starts a phrase with <c>ψ</c>.</summary>
    public static Phrase Psi() => Phrase.Empty.Add('ψ');
    /// <summary>Starts a phrase with <c>ω</c>.</summary>
    public static Phrase Omega() => Phrase.Empty.Add('ω');
}

/// <summary>
/// Chain-<b>continuing</b> tokens. Available with <c>using Stringly.Greek;</c>.
/// Hand-written macros, if any, live in a separate partial of this class.
/// </summary>
public static partial class GreekExtensions
{
    /// <summary>Continues a chain with <c>α</c>.</summary>
    public static Phrase Alpha(this Phrase p) => p.Add('α');
    /// <summary>Continues a chain with <c>β</c>.</summary>
    public static Phrase Beta(this Phrase p) => p.Add('β');
    /// <summary>Continues a chain with <c>γ</c>.</summary>
    public static Phrase Gamma(this Phrase p) => p.Add('γ');
    /// <summary>Continues a chain with <c>δ</c>.</summary>
    public static Phrase Delta(this Phrase p) => p.Add('δ');
    /// <summary>Continues a chain with <c>ε</c>.</summary>
    public static Phrase Epsilon(this Phrase p) => p.Add('ε');
    /// <summary>Continues a chain with <c>ζ</c>.</summary>
    public static Phrase Zeta(this Phrase p) => p.Add('ζ');
    /// <summary>Continues a chain with <c>η</c>.</summary>
    public static Phrase Eta(this Phrase p) => p.Add('η');
    /// <summary>Continues a chain with <c>θ</c>.</summary>
    public static Phrase Theta(this Phrase p) => p.Add('θ');
    /// <summary>Continues a chain with <c>ι</c>.</summary>
    public static Phrase Iota(this Phrase p) => p.Add('ι');
    /// <summary>Continues a chain with <c>κ</c>.</summary>
    public static Phrase Kappa(this Phrase p) => p.Add('κ');
    /// <summary>Continues a chain with <c>λ</c>.</summary>
    public static Phrase Lambda(this Phrase p) => p.Add('λ');
    /// <summary>Continues a chain with <c>μ</c>.</summary>
    public static Phrase Mu(this Phrase p) => p.Add('μ');
    /// <summary>Continues a chain with <c>ν</c>.</summary>
    public static Phrase Nu(this Phrase p) => p.Add('ν');
    /// <summary>Continues a chain with <c>ξ</c>.</summary>
    public static Phrase Xi(this Phrase p) => p.Add('ξ');
    /// <summary>Continues a chain with <c>ο</c>.</summary>
    public static Phrase Omicron(this Phrase p) => p.Add('ο');
    /// <summary>Continues a chain with <c>π</c>.</summary>
    public static Phrase Pi(this Phrase p) => p.Add('π');
    /// <summary>Continues a chain with <c>ρ</c>.</summary>
    public static Phrase Rho(this Phrase p) => p.Add('ρ');
    /// <summary>Continues a chain with <c>σ</c>.</summary>
    public static Phrase Sigma(this Phrase p) => p.Add('σ');
    /// <summary>Continues a chain with <c>τ</c>.</summary>
    public static Phrase Tau(this Phrase p) => p.Add('τ');
    /// <summary>Continues a chain with <c>υ</c>.</summary>
    public static Phrase Upsilon(this Phrase p) => p.Add('υ');
    /// <summary>Continues a chain with <c>φ</c>.</summary>
    public static Phrase Phi(this Phrase p) => p.Add('φ');
    /// <summary>Continues a chain with <c>χ</c>.</summary>
    public static Phrase Chi(this Phrase p) => p.Add('χ');
    /// <summary>Continues a chain with <c>ψ</c>.</summary>
    public static Phrase Psi(this Phrase p) => p.Add('ψ');
    /// <summary>Continues a chain with <c>ω</c>.</summary>
    public static Phrase Omega(this Phrase p) => p.Add('ω');
}
