// <auto-generated>
//     Generated by tools/generate.py — do not edit by hand.
//     Re-run: python3 tools/generate.py
// </auto-generated>

namespace Stringly;

public sealed partial class Phrase
{
    /// <summary>Appends <c>space</c>.</summary>
    public Phrase Space() => Add(' ');
    /// <summary>Appends <c>!</c>.</summary>
    public Phrase Bang() => Add('!');
    /// <summary>Appends <c>"</c>.</summary>
    public Phrase Quote() => Add('"');
    /// <summary>Appends <c>#</c>.</summary>
    public Phrase Hash() => Add('#');
    /// <summary>Appends <c>$</c>.</summary>
    public Phrase Dollar() => Add('$');
    /// <summary>Appends <c>%</c>.</summary>
    public Phrase Percent() => Add('%');
    /// <summary>Appends <c>&amp;</c>.</summary>
    public Phrase Amp() => Add('&');
    /// <summary>Appends <c>'</c>.</summary>
    public Phrase Apostrophe() => Add('\'');
    /// <summary>Appends <c>(</c>.</summary>
    public Phrase LParen() => Add('(');
    /// <summary>Appends <c>)</c>.</summary>
    public Phrase RParen() => Add(')');
    /// <summary>Appends <c>*</c>.</summary>
    public Phrase Star() => Add('*');
    /// <summary>Appends <c>+</c>.</summary>
    public Phrase Plus() => Add('+');
    /// <summary>Appends <c>,</c>.</summary>
    public Phrase Comma() => Add(',');
    /// <summary>Appends <c>-</c>.</summary>
    public Phrase Dash() => Add('-');
    /// <summary>Appends <c>.</c>.</summary>
    public Phrase Period() => Add('.');
    /// <summary>Appends <c>/</c>.</summary>
    public Phrase Slash() => Add('/');
    /// <summary>Appends <c>0</c>.</summary>
    public Phrase Zero() => Add('0');
    /// <summary>Appends <c>1</c>.</summary>
    public Phrase One() => Add('1');
    /// <summary>Appends <c>2</c>.</summary>
    public Phrase Two() => Add('2');
    /// <summary>Appends <c>3</c>.</summary>
    public Phrase Three() => Add('3');
    /// <summary>Appends <c>4</c>.</summary>
    public Phrase Four() => Add('4');
    /// <summary>Appends <c>5</c>.</summary>
    public Phrase Five() => Add('5');
    /// <summary>Appends <c>6</c>.</summary>
    public Phrase Six() => Add('6');
    /// <summary>Appends <c>7</c>.</summary>
    public Phrase Seven() => Add('7');
    /// <summary>Appends <c>8</c>.</summary>
    public Phrase Eight() => Add('8');
    /// <summary>Appends <c>9</c>.</summary>
    public Phrase Nine() => Add('9');
    /// <summary>Appends <c>:</c>.</summary>
    public Phrase Colon() => Add(':');
    /// <summary>Appends <c>;</c>.</summary>
    public Phrase Semicolon() => Add(';');
    /// <summary>Appends <c>&lt;</c>.</summary>
    public Phrase Lt() => Add('<');
    /// <summary>Appends <c>=</c>.</summary>
    public Phrase Eq() => Add('=');
    /// <summary>Appends <c>&gt;</c>.</summary>
    public Phrase Gt() => Add('>');
    /// <summary>Appends <c>?</c>.</summary>
    public Phrase Question() => Add('?');
    /// <summary>Appends <c>@</c>.</summary>
    public Phrase At() => Add('@');
    /// <summary>Appends <c>A</c>.</summary>
    public Phrase A() => Add('A');
    /// <summary>Appends <c>B</c>.</summary>
    public Phrase B() => Add('B');
    /// <summary>Appends <c>C</c>.</summary>
    public Phrase C() => Add('C');
    /// <summary>Appends <c>D</c>.</summary>
    public Phrase D() => Add('D');
    /// <summary>Appends <c>E</c>.</summary>
    public Phrase E() => Add('E');
    /// <summary>Appends <c>F</c>.</summary>
    public Phrase F() => Add('F');
    /// <summary>Appends <c>G</c>.</summary>
    public Phrase G() => Add('G');
    /// <summary>Appends <c>H</c>.</summary>
    public Phrase H() => Add('H');
    /// <summary>Appends <c>I</c>.</summary>
    public Phrase I() => Add('I');
    /// <summary>Appends <c>J</c>.</summary>
    public Phrase J() => Add('J');
    /// <summary>Appends <c>K</c>.</summary>
    public Phrase K() => Add('K');
    /// <summary>Appends <c>L</c>.</summary>
    public Phrase L() => Add('L');
    /// <summary>Appends <c>M</c>.</summary>
    public Phrase M() => Add('M');
    /// <summary>Appends <c>N</c>.</summary>
    public Phrase N() => Add('N');
    /// <summary>Appends <c>O</c>.</summary>
    public Phrase O() => Add('O');
    /// <summary>Appends <c>P</c>.</summary>
    public Phrase P() => Add('P');
    /// <summary>Appends <c>Q</c>.</summary>
    public Phrase Q() => Add('Q');
    /// <summary>Appends <c>R</c>.</summary>
    public Phrase R() => Add('R');
    /// <summary>Appends <c>S</c>.</summary>
    public Phrase S() => Add('S');
    /// <summary>Appends <c>T</c>.</summary>
    public Phrase T() => Add('T');
    /// <summary>Appends <c>U</c>.</summary>
    public Phrase U() => Add('U');
    /// <summary>Appends <c>V</c>.</summary>
    public Phrase V() => Add('V');
    /// <summary>Appends <c>W</c>.</summary>
    public Phrase W() => Add('W');
    /// <summary>Appends <c>X</c>.</summary>
    public Phrase X() => Add('X');
    /// <summary>Appends <c>Y</c>.</summary>
    public Phrase Y() => Add('Y');
    /// <summary>Appends <c>Z</c>.</summary>
    public Phrase Z() => Add('Z');
    /// <summary>Appends <c>[</c>.</summary>
    public Phrase LBracket() => Add('[');
    /// <summary>Appends <c>\</c>.</summary>
    public Phrase Backslash() => Add('\\');
    /// <summary>Appends <c>]</c>.</summary>
    public Phrase RBracket() => Add(']');
    /// <summary>Appends <c>^</c>.</summary>
    public Phrase Caret() => Add('^');
    /// <summary>Appends <c>_</c>.</summary>
    public Phrase Underscore() => Add('_');
    /// <summary>Appends <c>`</c>.</summary>
    public Phrase Backtick() => Add('`');
    /// <summary>Appends <c>a</c>.</summary>
    public Phrase a() => Add('a');
    /// <summary>Appends <c>b</c>.</summary>
    public Phrase b() => Add('b');
    /// <summary>Appends <c>c</c>.</summary>
    public Phrase c() => Add('c');
    /// <summary>Appends <c>d</c>.</summary>
    public Phrase d() => Add('d');
    /// <summary>Appends <c>e</c>.</summary>
    public Phrase e() => Add('e');
    /// <summary>Appends <c>f</c>.</summary>
    public Phrase f() => Add('f');
    /// <summary>Appends <c>g</c>.</summary>
    public Phrase g() => Add('g');
    /// <summary>Appends <c>h</c>.</summary>
    public Phrase h() => Add('h');
    /// <summary>Appends <c>i</c>.</summary>
    public Phrase i() => Add('i');
    /// <summary>Appends <c>j</c>.</summary>
    public Phrase j() => Add('j');
    /// <summary>Appends <c>k</c>.</summary>
    public Phrase k() => Add('k');
    /// <summary>Appends <c>l</c>.</summary>
    public Phrase l() => Add('l');
    /// <summary>Appends <c>m</c>.</summary>
    public Phrase m() => Add('m');
    /// <summary>Appends <c>n</c>.</summary>
    public Phrase n() => Add('n');
    /// <summary>Appends <c>o</c>.</summary>
    public Phrase o() => Add('o');
    /// <summary>Appends <c>p</c>.</summary>
    public Phrase p() => Add('p');
    /// <summary>Appends <c>q</c>.</summary>
    public Phrase q() => Add('q');
    /// <summary>Appends <c>r</c>.</summary>
    public Phrase r() => Add('r');
    /// <summary>Appends <c>s</c>.</summary>
    public Phrase s() => Add('s');
    /// <summary>Appends <c>t</c>.</summary>
    public Phrase t() => Add('t');
    /// <summary>Appends <c>u</c>.</summary>
    public Phrase u() => Add('u');
    /// <summary>Appends <c>v</c>.</summary>
    public Phrase v() => Add('v');
    /// <summary>Appends <c>w</c>.</summary>
    public Phrase w() => Add('w');
    /// <summary>Appends <c>x</c>.</summary>
    public Phrase x() => Add('x');
    /// <summary>Appends <c>y</c>.</summary>
    public Phrase y() => Add('y');
    /// <summary>Appends <c>z</c>.</summary>
    public Phrase z() => Add('z');
    /// <summary>Appends <c>{</c>.</summary>
    public Phrase LBrace() => Add('{');
    /// <summary>Appends <c>|</c>.</summary>
    public Phrase Pipe() => Add('|');
    /// <summary>Appends <c>}</c>.</summary>
    public Phrase RBrace() => Add('}');
    /// <summary>Appends <c>~</c>.</summary>
    public Phrase Tilde() => Add('~');
}
