// <auto-generated>
//     Generated by tools/generate.py — do not edit by hand.
//     Re-run: python3 tools/generate.py
// </auto-generated>

using Stringly;

namespace Stringly.Strings;

/// <summary>
/// String-extension twins so a chain can <b>start</b> from a string literal:
/// <c>"Let".M().e()</c>. The C# compiler resolves a method call against the
/// <i>static</i> type of the receiver, so to begin a chain on a <see cref="string"/>
/// the token must also exist as an extension on <see cref="string"/>. Each one lifts
/// the string into a <see cref="Phrase"/> (via the implicit conversion) and delegates
/// to the matching instance token — the real logic lives once on <see cref="Phrase"/>.
/// <para>
/// These live in their own <c>Stringly.Strings</c> namespace and are strictly opt-in.
/// Because <c>using</c> is not recursive, a plain <c>using Stringly;</c> (which you need
/// for the <see cref="Phrase"/> type and operators) does <b>not</b> pull these in and
/// leaves your strings untouched. Add <c>using Stringly.Strings;</c> only where you want
/// every string to grow ~95 token methods.
/// </para>
/// </summary>
public static class StringExtensions
{
    /// <summary>Lifts the string into a phrase and appends <c>space</c>.</summary>
    public static Phrase Space(this string s) => ((Phrase)s).Space();
    /// <summary>Lifts the string into a phrase and appends <c>!</c>.</summary>
    public static Phrase Bang(this string s) => ((Phrase)s).Bang();
    /// <summary>Lifts the string into a phrase and appends <c>"</c>.</summary>
    public static Phrase Quote(this string s) => ((Phrase)s).Quote();
    /// <summary>Lifts the string into a phrase and appends <c>#</c>.</summary>
    public static Phrase Hash(this string s) => ((Phrase)s).Hash();
    /// <summary>Lifts the string into a phrase and appends <c>$</c>.</summary>
    public static Phrase Dollar(this string s) => ((Phrase)s).Dollar();
    /// <summary>Lifts the string into a phrase and appends <c>%</c>.</summary>
    public static Phrase Percent(this string s) => ((Phrase)s).Percent();
    /// <summary>Lifts the string into a phrase and appends <c>&amp;</c>.</summary>
    public static Phrase Amp(this string s) => ((Phrase)s).Amp();
    /// <summary>Lifts the string into a phrase and appends <c>'</c>.</summary>
    public static Phrase Apostrophe(this string s) => ((Phrase)s).Apostrophe();
    /// <summary>Lifts the string into a phrase and appends <c>(</c>.</summary>
    public static Phrase LParen(this string s) => ((Phrase)s).LParen();
    /// <summary>Lifts the string into a phrase and appends <c>)</c>.</summary>
    public static Phrase RParen(this string s) => ((Phrase)s).RParen();
    /// <summary>Lifts the string into a phrase and appends <c>*</c>.</summary>
    public static Phrase Star(this string s) => ((Phrase)s).Star();
    /// <summary>Lifts the string into a phrase and appends <c>+</c>.</summary>
    public static Phrase Plus(this string s) => ((Phrase)s).Plus();
    /// <summary>Lifts the string into a phrase and appends <c>,</c>.</summary>
    public static Phrase Comma(this string s) => ((Phrase)s).Comma();
    /// <summary>Lifts the string into a phrase and appends <c>-</c>.</summary>
    public static Phrase Dash(this string s) => ((Phrase)s).Dash();
    /// <summary>Lifts the string into a phrase and appends <c>.</c>.</summary>
    public static Phrase Period(this string s) => ((Phrase)s).Period();
    /// <summary>Lifts the string into a phrase and appends <c>/</c>.</summary>
    public static Phrase Slash(this string s) => ((Phrase)s).Slash();
    /// <summary>Lifts the string into a phrase and appends <c>0</c>.</summary>
    public static Phrase Zero(this string s) => ((Phrase)s).Zero();
    /// <summary>Lifts the string into a phrase and appends <c>1</c>.</summary>
    public static Phrase One(this string s) => ((Phrase)s).One();
    /// <summary>Lifts the string into a phrase and appends <c>2</c>.</summary>
    public static Phrase Two(this string s) => ((Phrase)s).Two();
    /// <summary>Lifts the string into a phrase and appends <c>3</c>.</summary>
    public static Phrase Three(this string s) => ((Phrase)s).Three();
    /// <summary>Lifts the string into a phrase and appends <c>4</c>.</summary>
    public static Phrase Four(this string s) => ((Phrase)s).Four();
    /// <summary>Lifts the string into a phrase and appends <c>5</c>.</summary>
    public static Phrase Five(this string s) => ((Phrase)s).Five();
    /// <summary>Lifts the string into a phrase and appends <c>6</c>.</summary>
    public static Phrase Six(this string s) => ((Phrase)s).Six();
    /// <summary>Lifts the string into a phrase and appends <c>7</c>.</summary>
    public static Phrase Seven(this string s) => ((Phrase)s).Seven();
    /// <summary>Lifts the string into a phrase and appends <c>8</c>.</summary>
    public static Phrase Eight(this string s) => ((Phrase)s).Eight();
    /// <summary>Lifts the string into a phrase and appends <c>9</c>.</summary>
    public static Phrase Nine(this string s) => ((Phrase)s).Nine();
    /// <summary>Lifts the string into a phrase and appends <c>:</c>.</summary>
    public static Phrase Colon(this string s) => ((Phrase)s).Colon();
    /// <summary>Lifts the string into a phrase and appends <c>;</c>.</summary>
    public static Phrase Semicolon(this string s) => ((Phrase)s).Semicolon();
    /// <summary>Lifts the string into a phrase and appends <c>&lt;</c>.</summary>
    public static Phrase Lt(this string s) => ((Phrase)s).Lt();
    /// <summary>Lifts the string into a phrase and appends <c>=</c>.</summary>
    public static Phrase Eq(this string s) => ((Phrase)s).Eq();
    /// <summary>Lifts the string into a phrase and appends <c>&gt;</c>.</summary>
    public static Phrase Gt(this string s) => ((Phrase)s).Gt();
    /// <summary>Lifts the string into a phrase and appends <c>?</c>.</summary>
    public static Phrase Question(this string s) => ((Phrase)s).Question();
    /// <summary>Lifts the string into a phrase and appends <c>@</c>.</summary>
    public static Phrase At(this string s) => ((Phrase)s).At();
    /// <summary>Lifts the string into a phrase and appends <c>A</c>.</summary>
    public static Phrase A(this string s) => ((Phrase)s).A();
    /// <summary>Lifts the string into a phrase and appends <c>B</c>.</summary>
    public static Phrase B(this string s) => ((Phrase)s).B();
    /// <summary>Lifts the string into a phrase and appends <c>C</c>.</summary>
    public static Phrase C(this string s) => ((Phrase)s).C();
    /// <summary>Lifts the string into a phrase and appends <c>D</c>.</summary>
    public static Phrase D(this string s) => ((Phrase)s).D();
    /// <summary>Lifts the string into a phrase and appends <c>E</c>.</summary>
    public static Phrase E(this string s) => ((Phrase)s).E();
    /// <summary>Lifts the string into a phrase and appends <c>F</c>.</summary>
    public static Phrase F(this string s) => ((Phrase)s).F();
    /// <summary>Lifts the string into a phrase and appends <c>G</c>.</summary>
    public static Phrase G(this string s) => ((Phrase)s).G();
    /// <summary>Lifts the string into a phrase and appends <c>H</c>.</summary>
    public static Phrase H(this string s) => ((Phrase)s).H();
    /// <summary>Lifts the string into a phrase and appends <c>I</c>.</summary>
    public static Phrase I(this string s) => ((Phrase)s).I();
    /// <summary>Lifts the string into a phrase and appends <c>J</c>.</summary>
    public static Phrase J(this string s) => ((Phrase)s).J();
    /// <summary>Lifts the string into a phrase and appends <c>K</c>.</summary>
    public static Phrase K(this string s) => ((Phrase)s).K();
    /// <summary>Lifts the string into a phrase and appends <c>L</c>.</summary>
    public static Phrase L(this string s) => ((Phrase)s).L();
    /// <summary>Lifts the string into a phrase and appends <c>M</c>.</summary>
    public static Phrase M(this string s) => ((Phrase)s).M();
    /// <summary>Lifts the string into a phrase and appends <c>N</c>.</summary>
    public static Phrase N(this string s) => ((Phrase)s).N();
    /// <summary>Lifts the string into a phrase and appends <c>O</c>.</summary>
    public static Phrase O(this string s) => ((Phrase)s).O();
    /// <summary>Lifts the string into a phrase and appends <c>P</c>.</summary>
    public static Phrase P(this string s) => ((Phrase)s).P();
    /// <summary>Lifts the string into a phrase and appends <c>Q</c>.</summary>
    public static Phrase Q(this string s) => ((Phrase)s).Q();
    /// <summary>Lifts the string into a phrase and appends <c>R</c>.</summary>
    public static Phrase R(this string s) => ((Phrase)s).R();
    /// <summary>Lifts the string into a phrase and appends <c>S</c>.</summary>
    public static Phrase S(this string s) => ((Phrase)s).S();
    /// <summary>Lifts the string into a phrase and appends <c>T</c>.</summary>
    public static Phrase T(this string s) => ((Phrase)s).T();
    /// <summary>Lifts the string into a phrase and appends <c>U</c>.</summary>
    public static Phrase U(this string s) => ((Phrase)s).U();
    /// <summary>Lifts the string into a phrase and appends <c>V</c>.</summary>
    public static Phrase V(this string s) => ((Phrase)s).V();
    /// <summary>Lifts the string into a phrase and appends <c>W</c>.</summary>
    public static Phrase W(this string s) => ((Phrase)s).W();
    /// <summary>Lifts the string into a phrase and appends <c>X</c>.</summary>
    public static Phrase X(this string s) => ((Phrase)s).X();
    /// <summary>Lifts the string into a phrase and appends <c>Y</c>.</summary>
    public static Phrase Y(this string s) => ((Phrase)s).Y();
    /// <summary>Lifts the string into a phrase and appends <c>Z</c>.</summary>
    public static Phrase Z(this string s) => ((Phrase)s).Z();
    /// <summary>Lifts the string into a phrase and appends <c>[</c>.</summary>
    public static Phrase LBracket(this string s) => ((Phrase)s).LBracket();
    /// <summary>Lifts the string into a phrase and appends <c>\</c>.</summary>
    public static Phrase Backslash(this string s) => ((Phrase)s).Backslash();
    /// <summary>Lifts the string into a phrase and appends <c>]</c>.</summary>
    public static Phrase RBracket(this string s) => ((Phrase)s).RBracket();
    /// <summary>Lifts the string into a phrase and appends <c>^</c>.</summary>
    public static Phrase Caret(this string s) => ((Phrase)s).Caret();
    /// <summary>Lifts the string into a phrase and appends <c>_</c>.</summary>
    public static Phrase Underscore(this string s) => ((Phrase)s).Underscore();
    /// <summary>Lifts the string into a phrase and appends <c>`</c>.</summary>
    public static Phrase Backtick(this string s) => ((Phrase)s).Backtick();
    /// <summary>Lifts the string into a phrase and appends <c>a</c>.</summary>
    public static Phrase a(this string s) => ((Phrase)s).a();
    /// <summary>Lifts the string into a phrase and appends <c>b</c>.</summary>
    public static Phrase b(this string s) => ((Phrase)s).b();
    /// <summary>Lifts the string into a phrase and appends <c>c</c>.</summary>
    public static Phrase c(this string s) => ((Phrase)s).c();
    /// <summary>Lifts the string into a phrase and appends <c>d</c>.</summary>
    public static Phrase d(this string s) => ((Phrase)s).d();
    /// <summary>Lifts the string into a phrase and appends <c>e</c>.</summary>
    public static Phrase e(this string s) => ((Phrase)s).e();
    /// <summary>Lifts the string into a phrase and appends <c>f</c>.</summary>
    public static Phrase f(this string s) => ((Phrase)s).f();
    /// <summary>Lifts the string into a phrase and appends <c>g</c>.</summary>
    public static Phrase g(this string s) => ((Phrase)s).g();
    /// <summary>Lifts the string into a phrase and appends <c>h</c>.</summary>
    public static Phrase h(this string s) => ((Phrase)s).h();
    /// <summary>Lifts the string into a phrase and appends <c>i</c>.</summary>
    public static Phrase i(this string s) => ((Phrase)s).i();
    /// <summary>Lifts the string into a phrase and appends <c>j</c>.</summary>
    public static Phrase j(this string s) => ((Phrase)s).j();
    /// <summary>Lifts the string into a phrase and appends <c>k</c>.</summary>
    public static Phrase k(this string s) => ((Phrase)s).k();
    /// <summary>Lifts the string into a phrase and appends <c>l</c>.</summary>
    public static Phrase l(this string s) => ((Phrase)s).l();
    /// <summary>Lifts the string into a phrase and appends <c>m</c>.</summary>
    public static Phrase m(this string s) => ((Phrase)s).m();
    /// <summary>Lifts the string into a phrase and appends <c>n</c>.</summary>
    public static Phrase n(this string s) => ((Phrase)s).n();
    /// <summary>Lifts the string into a phrase and appends <c>o</c>.</summary>
    public static Phrase o(this string s) => ((Phrase)s).o();
    /// <summary>Lifts the string into a phrase and appends <c>p</c>.</summary>
    public static Phrase p(this string s) => ((Phrase)s).p();
    /// <summary>Lifts the string into a phrase and appends <c>q</c>.</summary>
    public static Phrase q(this string s) => ((Phrase)s).q();
    /// <summary>Lifts the string into a phrase and appends <c>r</c>.</summary>
    public static Phrase r(this string s) => ((Phrase)s).r();
    /// <summary>Lifts the string into a phrase and appends <c>s</c>.</summary>
    public static Phrase s(this string s) => ((Phrase)s).s();
    /// <summary>Lifts the string into a phrase and appends <c>t</c>.</summary>
    public static Phrase t(this string s) => ((Phrase)s).t();
    /// <summary>Lifts the string into a phrase and appends <c>u</c>.</summary>
    public static Phrase u(this string s) => ((Phrase)s).u();
    /// <summary>Lifts the string into a phrase and appends <c>v</c>.</summary>
    public static Phrase v(this string s) => ((Phrase)s).v();
    /// <summary>Lifts the string into a phrase and appends <c>w</c>.</summary>
    public static Phrase w(this string s) => ((Phrase)s).w();
    /// <summary>Lifts the string into a phrase and appends <c>x</c>.</summary>
    public static Phrase x(this string s) => ((Phrase)s).x();
    /// <summary>Lifts the string into a phrase and appends <c>y</c>.</summary>
    public static Phrase y(this string s) => ((Phrase)s).y();
    /// <summary>Lifts the string into a phrase and appends <c>z</c>.</summary>
    public static Phrase z(this string s) => ((Phrase)s).z();
    /// <summary>Lifts the string into a phrase and appends <c>{</c>.</summary>
    public static Phrase LBrace(this string s) => ((Phrase)s).LBrace();
    /// <summary>Lifts the string into a phrase and appends <c>|</c>.</summary>
    public static Phrase Pipe(this string s) => ((Phrase)s).Pipe();
    /// <summary>Lifts the string into a phrase and appends <c>}</c>.</summary>
    public static Phrase RBrace(this string s) => ((Phrase)s).RBrace();
    /// <summary>Lifts the string into a phrase and appends <c>~</c>.</summary>
    public static Phrase Tilde(this string s) => ((Phrase)s).Tilde();
}
