#!/usr/bin/env python3
"""Stringly token generator.

Emits the mechanical, one-line-per-token methods for the core library and the sample packs.
This is the "one-off script, commit the .cs" path from the design discussion: the token tables
change about once a decade, so a Source Generator would be overkill.

Re-run whenever a table below changes:

    python3 tools/generate.py

Generated files (all marked <auto-generated>):

  core   src/Stringly/Phrase.Tokens.g.cs   instance tokens on `partial class Phrase`
  core   src/Stringly/Say.Tokens.g.cs      static entry points on `partial class Say`
  core   src/Stringly/StringTokens.g.cs    string-extension twins (start a chain from a literal)
  nato   src/Stringly.Nato/Nato.g.cs       entries (class Start) + continuations (NatoExtensions)
  greek  src/Stringly.Greek/Greek.g.cs     entries (class Start) + continuations (GreekExtensions)
  emoji  src/Stringly.Emoji/Emoji.g.cs     entries (class Start) + continuations (EmojiExtensions)

Each pack's entry class is named `Start` (not after the namespace) so the import reads
`using static Stringly.Nato.Start;` rather than the stuttering `...Nato.Nato`.

Every token gets BOTH a static entry (so it can START a chain after `using static ...`) and an
instance continuation (so it can CONTINUE one). That symmetry is why no `Nothing()` seed is ever
needed — exactly how the core `Say`/`Phrase` pair already behaves.
"""

import os

HEADER = """// <auto-generated>
//     Generated by tools/generate.py — do not edit by hand.
//     Re-run: python3 tools/generate.py
// </auto-generated>
"""

# --- Core printable-ASCII table ------------------------------------------------------------------

SYMBOLS = {
    " ": "Space", "!": "Bang", '"': "Quote", "#": "Hash", "$": "Dollar", "%": "Percent",
    "&": "Amp", "'": "Apostrophe", "(": "LParen", ")": "RParen", "*": "Star", "+": "Plus",
    ",": "Comma", "-": "Dash", ".": "Period", "/": "Slash", ":": "Colon", ";": "Semicolon",
    "<": "Lt", "=": "Eq", ">": "Gt", "?": "Question", "@": "At", "[": "LBracket",
    "\\": "Backslash", "]": "RBracket", "^": "Caret", "_": "Underscore", "`": "Backtick",
    "{": "LBrace", "|": "Pipe", "}": "RBrace", "~": "Tilde",
}
DIGITS = ["Zero", "One", "Two", "Three", "Four", "Five", "Six", "Seven", "Eight", "Nine"]


def ascii_table():
    table = []
    for code in range(32, 127):
        ch = chr(code)
        if ch.isdigit():
            name = DIGITS[int(ch)]
        elif ch.isalpha():
            name = ch  # A() / a() — C# is case-sensitive, both legal and distinct
        else:
            name = SYMBOLS[ch]
        table.append((ch, name))
    return table


# --- Pack tables: method name -> single character it appends -------------------------------------

NATO = [
    ("Alfa", "A"), ("Bravo", "B"), ("Charlie", "C"), ("Delta", "D"), ("Echo", "E"),
    ("Foxtrot", "F"), ("Golf", "G"), ("Hotel", "H"), ("India", "I"), ("Juliett", "J"),
    ("Kilo", "K"), ("Lima", "L"), ("Mike", "M"), ("November", "N"), ("Oscar", "O"),
    ("Papa", "P"), ("Quebec", "Q"), ("Romeo", "R"), ("Sierra", "S"), ("Tango", "T"),
    ("Uniform", "U"), ("Victor", "V"), ("Whiskey", "W"), ("Xray", "X"), ("Yankee", "Y"),
    ("Zulu", "Z"),
]

GREEK = [
    ("Alpha", "α"), ("Beta", "β"), ("Gamma", "γ"), ("Delta", "δ"), ("Epsilon", "ε"),
    ("Zeta", "ζ"), ("Eta", "η"), ("Theta", "θ"), ("Iota", "ι"), ("Kappa", "κ"),
    ("Lambda", "λ"), ("Mu", "μ"), ("Nu", "ν"), ("Xi", "ξ"), ("Omicron", "ο"),
    ("Pi", "π"), ("Rho", "ρ"), ("Sigma", "σ"), ("Tau", "τ"), ("Upsilon", "υ"),
    ("Phi", "φ"), ("Chi", "χ"), ("Psi", "ψ"), ("Omega", "ω"),
]

# Emoji are strings, not chars: most are surrogate pairs (outside the BMP) and some are
# multi-codepoint (e.g. ❤️ = heart + variation selector). Names deliberately avoid the core
# token names (no "Star": Phrase already has Star() for '*', and an instance method would
# silently win over an extension of the same name).
EMOJI = [
    ("Grin", "😀"), ("Joy", "😂"), ("Wink", "😉"), ("Cool", "😎"), ("Cry", "😢"),
    ("Heart", "❤️"), ("ThumbsUp", "👍"), ("ThumbsDown", "👎"), ("Clap", "👏"), ("Wave", "👋"),
    ("Fire", "🔥"), ("Rocket", "🚀"), ("Party", "🎉"), ("Hundred", "💯"), ("Sparkles", "✨"),
    ("Eyes", "👀"), ("Skull", "💀"), ("Poop", "💩"), ("Check", "✅"), ("Cross", "❌"),
    ("Cat", "🐱"), ("Dog", "🐶"), ("Pizza", "🍕"), ("Coffee", "☕"), ("Beer", "🍺"),
    ("Rainbow", "🌈"), ("Sun", "☀️"), ("Moon", "🌙"),
]


# --- Emit helpers --------------------------------------------------------------------------------

def char_literal(ch):
    if ch == "\\":
        return "'\\\\'"
    if ch == "'":
        return "'\\''"
    return f"'{ch}'"


def doc(ch):
    return {"<": "&lt;", ">": "&gt;", "&": "&amp;", " ": "space"}.get(ch, ch)


def emit_core_instance(table):
    lines = [HEADER, "namespace Stringly;", "", "public sealed partial class Phrase", "{"]
    for ch, name in table:
        lines.append(f"    /// <summary>Appends <c>{doc(ch)}</c>.</summary>")
        lines.append(f"    public Phrase {name}() => Add({char_literal(ch)});")
    lines.append("}")
    return "\n".join(lines) + "\n"


def emit_core_entries(table):
    lines = [HEADER, "namespace Stringly;", "", "public static partial class Say", "{"]
    for ch, name in table:
        lines.append(f"    /// <summary>Starts a phrase with <c>{doc(ch)}</c>.</summary>")
        lines.append(f"    public static Phrase {name}() => Phrase.Empty.{name}();")
    lines.append("}")
    return "\n".join(lines) + "\n"


def emit_string_extensions(table):
    """String-extension twins: let a chain start from a string literal, e.g. "Let".M().e()."""
    lines = [HEADER, "using Stringly;", "", "namespace Stringly.Strings;", ""]
    lines.append("/// <summary>")
    lines.append("/// String-extension twins so a chain can <b>start</b> from a string literal:")
    lines.append("/// <c>\"Let\".M().e()</c>. The C# compiler resolves a method call against the")
    lines.append("/// <i>static</i> type of the receiver, so to begin a chain on a <see cref=\"string\"/>")
    lines.append("/// the token must also exist as an extension on <see cref=\"string\"/>. Each one lifts")
    lines.append("/// the string into a <see cref=\"Phrase\"/> (via the implicit conversion) and delegates")
    lines.append("/// to the matching instance token — the real logic lives once on <see cref=\"Phrase\"/>.")
    lines.append("/// <para>")
    lines.append("/// These live in their own <c>Stringly.Strings</c> namespace and are strictly opt-in.")
    lines.append("/// Because <c>using</c> is not recursive, a plain <c>using Stringly;</c> (which you need")
    lines.append("/// for the <see cref=\"Phrase\"/> type and operators) does <b>not</b> pull these in and")
    lines.append("/// leaves your strings untouched. Add <c>using Stringly.Strings;</c> only where you want")
    lines.append("/// every string to grow ~95 token methods.")
    lines.append("/// </para>")
    lines.append("/// </summary>")
    lines.append("public static class StringExtensions")
    lines.append("{")
    for ch, name in table:
        lines.append(f"    /// <summary>Lifts the string into a phrase and appends <c>{doc(ch)}</c>.</summary>")
        lines.append(f"    public static Phrase {name}(this string s) => ((Phrase)s).{name}();")
    lines.append("}")
    return "\n".join(lines) + "\n"


def string_literal(value):
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def emit_pack(namespace, entry_class, ext_class, table, kind="char"):
    """One file: a plain static entry class (chain starters) + an extension class (continuations).

    kind="char"   — each value is a single UTF-16 char, emitted as Add('x'). Good for ASCII/BMP.
    kind="string" — each value is a string (may be a surrogate pair / multi-codepoint, like emoji),
                    emitted as Add("..."). Single chars don't fit in a char literal there.
    """
    def add_call(value):
        return f"Add({char_literal(value)})" if kind == "char" else f"Add({string_literal(value)})"

    lines = [HEADER, f"namespace Stringly.{namespace};", ""]

    lines.append("/// <summary>")
    lines.append(f"/// Chain-<b>starting</b> entries. Import with <c>using static Stringly.{namespace}.{entry_class};</c>")
    lines.append("/// to begin a chain with a bare call.")
    lines.append("/// </summary>")
    lines.append(f"public static class {entry_class}")
    lines.append("{")
    for name, value in table:
        lines.append(f"    /// <summary>Starts a phrase with <c>{doc(value)}</c>.</summary>")
        lines.append(f"    public static Phrase {name}() => Phrase.Empty.{add_call(value)};")
    lines.append("}")
    lines.append("")

    lines.append("/// <summary>")
    lines.append(f"/// Chain-<b>continuing</b> tokens. Available with <c>using Stringly.{namespace};</c>.")
    lines.append("/// Hand-written macros live in a separate partial of this class.")
    lines.append("/// </summary>")
    lines.append(f"public static partial class {ext_class}")
    lines.append("{")
    for name, value in table:
        lines.append(f"    /// <summary>Continues a chain with <c>{doc(value)}</c>.</summary>")
        lines.append(f"    public static Phrase {name}(this Phrase p) => p.{add_call(value)};")
    lines.append("}")
    return "\n".join(lines) + "\n"


def write(path, text):
    with open(path, "w", encoding="utf-8") as f:
        f.write(text)


def main():
    here = os.path.dirname(os.path.abspath(__file__))
    root = os.path.normpath(os.path.join(here, ".."))

    ascii_ = ascii_table()
    write(os.path.join(root, "src", "Stringly", "Phrase.Tokens.g.cs"), emit_core_instance(ascii_))
    write(os.path.join(root, "src", "Stringly", "Say.Tokens.g.cs"), emit_core_entries(ascii_))
    write(os.path.join(root, "src", "Stringly", "StringTokens.g.cs"), emit_string_extensions(ascii_))
    write(os.path.join(root, "src", "Stringly.Nato", "Nato.g.cs"),
          emit_pack("Nato", "Start", "NatoExtensions", NATO))
    write(os.path.join(root, "src", "Stringly.Greek", "Greek.g.cs"),
          emit_pack("Greek", "Start", "GreekExtensions", GREEK))
    write(os.path.join(root, "src", "Stringly.Emoji", "Emoji.g.cs"),
          emit_pack("Emoji", "Start", "EmojiExtensions", EMOJI, kind="string"))

    print(f"Generated: core={len(ascii_)} nato={len(NATO)} greek={len(GREEK)} emoji={len(EMOJI)} token methods")


if __name__ == "__main__":
    main()
